/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CameraView */

#ifndef _Included_CoverCamView
#define _Included_CoverCamView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CameraView
 * Method:    decode
 * Signature: (Landroid/graphics/Bitmap;[B)V
 */
JNIEXPORT void JNICALL Java_com_vm_covercam_CoverCamView_decode
  (JNIEnv *, jobject, jobject, jbyteArray, jint);


#ifdef __cplusplus
}
#endif
#endif
